services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  springboot-app:
    build: .
    container_name: springboot-app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: '${MYSQL_URL}'
      SPRING_DATASOURCE_USERNAME: '${MYSQL_USERNAME}'
      SPRING_DATASOURCE_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
