spring:
  application:
    name=web:
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jwt:
  secret: b7e29d7bc4c8704077549d755d01139de165e4bde39bbb16275c773250823125
#  공개 금지 (공개시 ignore에 추가 필요)