spring:
  profiles:
    active: ${profile}
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        logging.level:
          org.hibernate.SQL: debug
        #  org.hibernate.type: trace

jwt:
  secret: ${jwt}
#  공개 금지 (공개시 ignore에 추가 필요)

logging:
  level:
    root: INFO